### ISSUE TITLE
Question about carpet recognition

### ISSUE THREAD

**Issue by wrfokokokwrf** [acconeer/acconeer-a121-carpet-detection#1]
How do I burn a python program of acconeer-a121-carpet-detection to the chip of A121.
Thank you.

**Comment by AlbTommy** [comment]
Hi,

By the 'burn', do you mean compiling C-code for an embedded application? If so, we do not have any support for that as of today. You can try generating C code using Keras2C for instance(https://github.com/f0uriest/keras2c), and then compile it for you target device.

Let me know if you have any further questions.
